# States
STATE_START = 1
STATE_NAME = 2
STATE_STATS = 3
STATE_PICK_UP_WEAPON_FIRST_LAYER = 4
STATE_DIRECTION_DECISION_FIRST_LAYER = 5
STATE_ROOM_SECOND_LAYER = 6
# ... More states will be added here
STATE_HELP = 'help'
STATE_STATS = 'stats'
